CREATE DATABASE SEU_IS_20_ICT_084;
USE SEU_IS_20_ICT_084;

CREATE TABLE bookICT084 (
	book_ID INT(10) AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL,
	ISBN VARCHAR(20) NOT NULL,
	price DECIMAL(10, 2) NOT NULL,
	description TEXT
);



